version: '3.8'

services:
  app:
    build: .
    container_name: app
    ports:
      - "${APP_PORT}:${APP_CONTAINER_PORT}"
    environment:
      - APP_API_KEY=${APP_API_KEY}
      - APP_DB_CONNECTION=${APP_DB_CONNECTION}
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${DB_CONTAINER_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
